title: "WP 4 Docker"
tagline: "WordPress & ClassicPress Development"

primary:
  - title: "phpMyAdmin"
    url: "/phpmyadmin"
  - title: "PHPInfo"
    url: "/phpinfo"

social:
  - title: "Facebook"
    url: "https://www.facebook.com/benlumia007"
    svg: "/svg/facebook-brands.svg.php"
  - title: "Twitter"
    url: "https://twitter.com/benlumia007"
    svg: "/svg/twitter-brands.svg.php"
  - title: "WordPress"
    url: "https://profiles.wordpress.org/benlumia007/"
    svg: "/svg/wordpress-simple-brands.svg.php"
